name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekcout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "major:"
        minor_pattern: "feat:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build Docker image & Push Docker image
      env:
        DIR_APP: ${{ secrets.DIR_APP }}
        PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      run: |
        docker build -t $DOCKER_USER/$PROJECT_NAME:$NEW_VERSION $DIR_APP/.
        docker build -t $DOCKER_USER/$PROJECT_NAME:latest $DIR_APP/.
        docker push $DOCKER_USER/$PROJECT_NAME:$NEW_VERSION 
        docker push $DOCKER_USER/$PROJECT_NAME:latest 
    
    
